const KEY='savingsQuest_v3',money=n=>'$'+Number(n||0).toFixed(2),today=()=>new Date().toISOString().slice(0,10),uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
const defaults={baseline:357.84,actual:357.84,groceries:55,savings:25,flexFloor:35,week:1,envelopes:[{id:uid(),name:'Car Insurance',target:338.25,balance:0,weekly:84.56,dueDay:1,history:[]},{id:uid(),name:'National Debt Relief',target:100.50,balance:0,weekly:25.13,dueDay:5,history:[]}],repayments:[],debts:[{id:uid(),provider:'Affirm',name:'Affirm 1',payment:12.45,balance:69.28,kind:'monthly'},{id:uid(),provider:'Affirm',name:'Affirm 2',payment:19.41,balance:272.55,kind:'monthly'},{id:uid(),provider:'Affirm',name:'Affirm 3',payment:13.11,balance:122.54,kind:'monthly'},{id:uid(),provider:'Klarna',name:'Klarna total',payment:29.73,balance:73.29,kind:'biweekly',parts:[9.46,6.71,4.41,6.25,2.90]}],weeks:[]};
let state=JSON.parse(localStorage.getItem(KEY)||'null')||defaults,deferredPrompt=null;state.theme=state.theme||'dark';const save=()=>localStorage.setItem(KEY,JSON.stringify(state));function toast(t){let x=document.getElementById('toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',2100)}function closeModal(id){document.getElementById(id).classList.remove('show')}window.closeModal=closeModal;

function applyTheme(theme){
  state.theme=theme==='light'?'light':'dark';
  document.documentElement.setAttribute('data-theme',state.theme);
  const b=document.getElementById('themeToggle');
  if(b)b.textContent=state.theme==='dark'?'☀️ Light':'🌙 Dark';
  document.querySelector('meta[name="theme-color"]')?.setAttribute('content',state.theme==='dark'?'#09070d':'#7757D9');
  save();
}
function toggleTheme(){applyTheme(state.theme==='dark'?'light':'dark')}
window.toggleTheme=toggleTheme;

function smartAllocate(extra){let left=extra,m=[];for(const e of [...state.envelopes].sort((a,b)=>(a.balance/a.target)-(b.balance/b.target))){if(left<=0)break;let need=Math.max(0,e.target-e.balance);if(need){let a=Math.min(left,need);m.push({type:'envelope',id:e.id,name:e.name,amount:a});left-=a}}for(const r of state.repayments.filter(r=>!r.paid)){if(left<=0)break;let a=Math.min(left,r.owed);m.push({type:'repayment',id:r.id,name:'Repay '+r.envelopeName,amount:a});left-=a}for(const d of [...state.debts].filter(d=>d.balance>0).sort((a,b)=>a.balance-b.balance)){if(left<=0)break;let a=Math.min(left,d.balance);m.push({type:'debt',id:d.id,name:d.name,amount:a});left-=a}if(left>0)m.push({type:'savings',name:'Savings',amount:left});return m}
function calc(){let actual=+actualPay.value||0,baseline=+baselinePay.value||357.84;state.actual=actual;state.baseline=baseline;let repaymentTotal=state.repayments.filter(r=>!r.paid).reduce((s,r)=>s+r.owed,0),envWeekly=state.envelopes.reduce((s,e)=>s+(+e.weekly||0),0),debtMinimum=state.debts.reduce((s,d)=>s+(d.kind==='monthly'?(+d.payment||0)/4.345:(+d.payment||0)/2),0),fixed=Math.min(actual,envWeekly+debtMinimum+repaymentTotal),groceries=Math.min(state.groceries,Math.max(0,actual-fixed)),savings=Math.min(state.savings,Math.max(0,actual-fixed-groceries)),flexible=Math.max(0,Math.min(state.flexFloor,actual-fixed-groceries-savings)),extra=Math.max(0,actual-baseline);return{actual,baseline,envWeekly,debtMinimum,repaymentTotal,groceries,savings,flexible,extra,smart:smartAllocate(extra)}}
function render(){let p=calc();paycheckDisplay.textContent=money(p.actual);paycheckNote.textContent=`Typical take-home baseline: ${money(p.baseline)}${p.extra>0?' • Extra this week: +'+money(p.extra):''}`;let a=[['Bills + envelopes',p.envWeekly,'#7757d9'],['Groceries',p.groceries,'#91c6ff'],['Savings',p.savings,'#a8e5cd'],['Flexible',p.flexible,'#f4aec7']];allocationCards.innerHTML=a.map(x=>`<div class="abox"><span class="mini muted">${x[0]}</span><strong>${money(x[1])}</strong><div class="bar" style="background:${x[2]}"></div></div>`).join('');smartExtra.innerHTML=p.extra>0?`<b>Smart Extra Pay: +${money(p.extra)}</b><div class="mini" style="margin-top:6px">${p.smart.map(x=>`${money(x.amount)} → ${x.name}`).join(' • ')}</div><button class="btn secondary" style="margin-top:9px" onclick="applySmartExtra()">Apply smart allocation</button>`:'<b>Normal week</b><div class="mini" style="margin-top:6px">No extra-pay decision is needed.</div>';renderEnvelopes();renderDebts();renderRepayments();renderHistory();guideText.textContent=p.extra>0?`You brought home ${money(p.extra)} more than your usual baseline. Savings Quest will strengthen the most important category first.`:'Your plan stays based on your usual take-home so rare higher checks do not quietly increase spending.';priorityText.textContent=state.repayments.some(r=>!r.paid)?'Keep bill envelopes safe, clear envelope repayments, then attack the smallest payoff balance.':state.envelopes.some(e=>e.balance<e.target)?'Fund bill envelopes first, then attack the smallest Affirm/Klarna payoff balance.':state.debts.some(d=>d.balance>0)?'Envelopes are healthy, so extra money can attack the smallest payoff balance.':'Everything is handled; extra money can go to savings.';score.textContent=Math.max(0,100-state.repayments.filter(r=>!r.paid).length*4);totalDebtPill.textContent='Current payoff: '+money(state.debts.reduce((s,d)=>s+d.balance,0));save()}
function renderEnvelopes(){envelopeList.innerHTML=state.envelopes.map(e=>{let pct=Math.min(100,e.target?e.balance/e.target*100:0);return`<div class="item"><div class="row"><div><b>${e.name}</b><div class="mini muted">Due day ${e.dueDay||'—'} • weekly ${money(e.weekly)}</div></div><b>${money(e.balance)} / ${money(e.target)}</b></div><div class="progress"><span style="width:${pct}%"></span></div><div class="row"><span class="mini muted">${pct.toFixed(0)}% funded</span><div><button class="btn secondary" onclick="fundEnvelope('${e.id}')">+ Weekly amount</button> <button class="btn soft" onclick="openBorrow('${e.id}')">Borrow</button></div></div></div>`}).join('')||'<div class="muted">No envelopes yet.</div>'}
function renderDebts(){let s=[...state.debts].sort((a,b)=>a.balance-b.balance),t=s.find(d=>d.balance>0);debtList.innerHTML=s.map(d=>`<div class="item"><div class="row"><div><b>${d.provider} • ${d.name}</b><div class="mini muted">${d.kind==='monthly'?'Monthly payment':'Bi-weekly group'} ${money(d.payment)} ${t&&t.id===d.id?'• 🎯 Targeted':''}</div></div><b>${money(d.balance)}</b></div>${d.parts?`<div class="mini muted" style="margin-top:8px">Payments: ${d.parts.map(money).join(' · ')}</div>`:''}<button class="btn secondary" style="margin-top:9px" onclick="recordDebtPayment('${d.id}')">Record extra payment</button></div>`).join('')}
function renderRepayments(){let o=state.repayments.filter(r=>!r.paid);repaymentList.innerHTML=o.length?o.map(r=>`<div class="item"><b>${r.envelopeName}</b><div class="mini muted">Borrowed ${money(r.borrowed)} + 1% = ${money(r.owed)}</div><button class="btn secondary" style="margin-top:8px" onclick="repay('${r.id}')">Mark repaid</button></div>`).join(''):'<div class="muted mini">No repayments due.</div>'}
function renderHistory(){let rows=[];state.envelopes.forEach(e=>(e.history||[]).slice().reverse().forEach(h=>rows.push({...h,envelope:e.name})));rows.sort((a,b)=>(b.date||'').localeCompare(a.date||''));historyList.innerHTML=rows.length?rows.map(h=>`<div class="item"><div class="row"><div><b>${h.envelope}</b><div class="mini muted">${h.date} • Week ${h.week||'—'} • ${h.type}</div></div><b>${h.type==='borrow'?'-':'+'}${money(h.amount)}</b></div></div>`).join(''):'<div class="muted">No weekly contribution history yet.</div>'}
function fundEnvelope(id){let e=state.envelopes.find(x=>x.id===id),a=Math.min(+e.weekly||0,Math.max(0,e.target-e.balance));e.balance+=a;e.history.push({date:today(),week:state.week,type:'weekly contribution',amount:a});render();toast(`${money(a)} added to ${e.name}`)}function openBorrow(id){borrowEnvId.value=id;borrowAmount.value='';borrowModal.classList.add('show')}window.openBorrow=openBorrow;window.fundEnvelope=fundEnvelope;
confirmBorrow.onclick=()=>{let e=state.envelopes.find(x=>x.id===borrowEnvId.value),a=+borrowAmount.value||0;if(!e||a<=0||a>e.balance)return toast('Enter an amount available in this envelope.');e.balance-=a;e.history.push({date:today(),week:state.week,type:'borrow',amount:a});state.repayments.push({id:uid(),envelopeId:e.id,envelopeName:e.name,borrowed:a,owed:Math.round(a*1.01*100)/100,paid:false,date:today()});closeModal('borrowModal');render();toast('Repayment scheduled: '+money(a*1.01))};
function repay(id){let r=state.repayments.find(x=>x.id===id),e=state.envelopes.find(x=>x.id===r.envelopeId);e.balance+=r.owed;e.history.push({date:today(),week:state.week+1,type:'repayment + 1%',amount:r.owed});r.paid=true;render();toast('Envelope repaid.')}window.repay=repay;
function recordDebtPayment(id){let d=state.debts.find(x=>x.id===id),v=prompt(`Extra payment for ${d.name} (current payoff ${money(d.balance)}):`),a=+v||0;if(a<=0)return;d.balance=Math.max(0,d.balance-a);render();toast('Debt payoff updated.')}window.recordDebtPayment=recordDebtPayment;
function applySmartExtra(){let p=calc();p.smart.forEach(m=>{if(m.type==='envelope'){let e=state.envelopes.find(x=>x.id===m.id);e.balance+=m.amount;e.history.push({date:today(),week:state.week,type:'smart extra',amount:m.amount})}else if(m.type==='repayment'){let r=state.repayments.find(x=>x.id===m.id),e=state.envelopes.find(x=>x.id===r.envelopeId),pay=Math.min(r.owed,m.amount);e.balance+=pay;r.owed=Math.max(0,r.owed-pay);if(r.owed<.005)r.paid=true}else if(m.type==='debt'){let d=state.debts.find(x=>x.id===m.id);d.balance=Math.max(0,d.balance-m.amount)}});state.weeks.push({date:today(),week:state.week,actual:state.actual,baseline:state.baseline,extra:p.extra,moves:p.smart});state.week++;render();toast('Smart extra allocation applied.')}window.applySmartExtra=applySmartExtra;
addEnvelopeBtn.onclick=()=>envelopeModal.classList.add('show');saveEnvelopeBtn.onclick=()=>{state.envelopes.push({id:uid(),name:envName.value.trim()||'New Envelope',target:+envTarget.value||0,balance:+envBalance.value||0,weekly:+envWeekly.value||0,dueDay:+envDueDay.value||0,history:[]});closeModal('envelopeModal');render();toast('Envelope added.')};saveSettings.onclick=()=>{state.groceries=+groceryTarget.value||0;state.savings=+savingTarget.value||0;state.flexFloor=+flexFloor.value||0;render();toast('Settings saved.')};recalcBtn.onclick=render;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');['envelopes','debts','history'].forEach(t=>document.getElementById(t+'Panel').style.display=t===b.dataset.tab?'block':'none')});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.style.display='inline-block'});installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');baselinePay.value=state.baseline;actualPay.value=state.actual;groceryTarget.value=state.groceries;savingTarget.value=state.savings;flexFloor.value=state.flexFloor;themeToggle.onclick=toggleTheme;applyTheme(state.theme);render();